Makefile.min_deps: add kdevops-install-deps target
This ensures based packages are installed using distro package manager
method when minimum dependencies are not found.

Signed-off-by: Daniel Gomez <da.gomez@samsung.com>

diff --git a/Makefile.min_deps b/Makefile.min_deps
--- a/Makefile.min_deps
+++ b/Makefile.min_deps
@@ -5,11 +5,10 @@
 # have something more elaborate, like a version check add it to its
 # own file as we do with scripts/version_check/ansible-playbook
 
-BINARY_DEPS :=
-BINARY_DEPS += sudo
-BINARY_DEPS += make
-BINARY_DEPS += nc
-BINARY_DEPS += ansible-playbook
+BINARY_DEPS := sudo make ansible-playbook
+DEBIAN_PACKAGE_DEPS := sudo make netcat-traditional ansible
+SUSE_PACKAGE_DEPS := sudo make nc ansible
+REDHAT_PACKAGE_DEPS := sudo make ncat ansible
 
 BINARY_DEPS_VCHECKS := $(subst $(TOPDIR)/,,$(wildcard $(TOPDIR)/scripts/version_check/*))
 
@@ -31,7 +30,27 @@ $(BINARY_DEPS):
 	$(Q)echo Verifying $@ ...
 	$(Q)set -e ; which $@ > /dev/null || ( \
 		echo Missing dependency: $@ ;\
+		echo Run 'make kdevops-install-min-deps' to install missing dependencies ;\
 	false)
+
+install_package_deps:
+	@echo "Detecting Linux distribution..."
+	@if [ -f /etc/debian_version ]; then \
+		echo "Detected Debian-based distro."; \
+		sudo apt update && sudo apt install -y $(DEBIAN_PACKAGE_DEPS); \
+	elif [ -f /etc/redhat-release ]; then \
+		echo "Detected Red Hat-based distro."; \
+		sudo yum install -y $(REDHAT_PACKAGE_DEPS); \
+	elif [ -f /etc/SuSE-release ]; then \
+		echo "Detected SUSE-based distro."; \
+		sudo zypper install -y $(SUSE_PACKAGE_DEPS); \
+	else \
+		echo "Unsupported Linux distribution."; \
+		exit 1; \
+	fi
+
+kdevops-install-min-deps: install_package_deps
+PHONY += kdevops-install-min-deps
 
 $(KDEVOPS_DEPCHECK): $(DYNAMIC_DEPS)
 	$(Q)echo The current minimum kdevops expected dependencies are met.
